// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, base, definePromiseProperty, proxyAll, proxyBuilder, synchronize, _i, _len, _ref,
    __slice = [].slice;

  Promise = require("bluebird");

  module.exports = Promise;

  synchronize = function(asyncFn) {
    return function() {
      var args, fnThis;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      fnThis = this === asyncFn && global || this;
      return Promise.promisify(asyncFn, fnThis).apply(fnThis, args);
    };
  };

  proxyAll = function(src, target, proxyFn) {
    var key, _fn, _i, _len, _ref;
    _ref = Object.keys(src);
    _fn = function(key) {
      if (Object.prototype[key] != null) {
        return;
      }
      if (Object.getOwnPropertyDescriptor(src, key).get != null) {
        return;
      }
      if (typeof src[key] !== 'function') {
        return;
      }
      return target[key] = proxyFn(key);
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      _fn(key);
    }
    return target;
  };

  proxyBuilder = function(that) {
    var func, result;
    result = typeof that === 'function' ? (func = synchronize(that), Object.getPrototypeOf(that) !== Function.prototype ? func.__proto__ = Object.getPrototypeOf(that).promise : void 0, func) : Object.create(Object.getPrototypeOf(that) && Object.getPrototypeOf(that).promise || Object.prototype);
    result.that = that;
    proxyAll(that, result, function(key) {
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return this.that[key].promise.apply(this.that, args);
      };
    });
    return result;
  };

  definePromiseProperty = function(target, factory) {
    var cacheKey;
    if (target.hasOwnProperty("promise")) {
      return;
    }
    cacheKey = "__songbird__";
    return Object.defineProperty(target, "promise", {
      enumerable: false,
      set: function(value) {
        delete this[cacheKey];
        return Object.defineProperty(this, "promise", {
          value: value,
          writable: true,
          configurable: true,
          enumerable: true
        });
      },
      get: function() {
        if (!(Object.prototype.hasOwnProperty.call(this, cacheKey) && this[cacheKey])) {
          Object.defineProperty(this, cacheKey, {
            value: factory(this),
            writable: true,
            configurable: true,
            enumerable: false
          });
        }
        return this[cacheKey];
      }
    });
  };

  _ref = [Object.prototype, Function.prototype];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    base = _ref[_i];
    definePromiseProperty(base, proxyBuilder);
  }

}).call(this);
